### ISSUE TITLE
error occur when create volumeMapper

### ISSUE THREAD

**Issue by xiasun** [fblupi/rendering-volume-from-dicom-vtk#1]
It break here on vtkFixedPointVolumeRayCastMapper, line 706.
`this->ImageDisplayHelper->PreMultipliedColorsOn();`

VTK version 7.1

**Comment by fblupi** [comment]
When I created this example I used VTK 7.0. I'll check it with the new VTK version.

**Comment by fblupi** [comment]
It worked ok to me on Windows 10 64 bits with Visual Studio Community 2015 and VTK 7.1.0

Maybe you have not compiled correctly VTK with CMake. Try checking these options:

* VTK_Group_Imaging
* Module_vtkDICOM

Which is your OS and C++ compiler?

**Comment by xiasun** [comment]
I'll try it further, its not the problem of your code I guess, btw, how can I know whether I have build VTK_Group_Imaging and Module_vtkDICOM? I don't remember whether I have checked them...

**Comment by fblupi** [comment]
You can use ccmake or cmake-gui to check it
